### ISSUE TITLE
[BUG] Wind umbrellas

### ISSUE THREAD

**Issue by GekanAPK** [FuryFight3r/dgrp_mcdonaldsjob#1]
Can you remove the wind effect in the umbrellas inside the room?

**Comment by FuryFight3r** [comment]
Thank you for creating an issue, however this is not a bug, its a minor detail, the seats used are ouside seats, so if you do not like the wind effect, please use different seats, I did not create the ymap for the building so its not fair for me to modify and reupload a modified version, by all means if little details upset you that much you are more than welcome to fix them yourself and create a pull request.
All the best, FuryFight3r

**Comment by GekanAPK** [comment]
Another issues, why raining inside?

**Comment by FuryFight3r** [comment]
Again that is a problem with the building, as stated earlier, I am not the creator of the building I only put everything together and did all the scripting, if these are entirely necessary things that need to be dealt with, please get in contact with RibSoSay the developer of the building and get him to fix them.

https://www.gta5-mods.com/maps/mcdonalds-building-with-interior-and-drive-through-v-0-01
