### ISSUE TITLE
U can job when u dont have setjob

### ISSUE THREAD

**Issue by davidcaky11** [FuryFight3r/dgrp_mcdonaldsjob#2]
Hello i dont see a marker ... but when i go to coords i can work at mcdonald without setjob.. when i setjob marker is visible but i wanna remove the all players can do a job ... but only setjob guys can do

**Comment by FuryFight3r** [comment]
Please next time only use the templates to report problems. I will look into this.
https://github.com/FuryFight3r/dgrp_mcdonaldsjob/issues/new?assignees=FuryFight3r&labels=bug&template=bug-template.md&title=%5BBUG%5D

**Comment by davidcaky11** [comment]
Okey next time i will lok into template bug can u watch it pls?

**Comment by FuryFight3r** [comment]
No problem, already fixed, uploading now.

**Comment by davidcaky11** [comment]
One more question how to take from registry i dont wanna have this jobs for everyone but like fraction

**Comment by FuryFight3r** [comment]
> One more question how to take from registry i dont wanna have this jobs for everyone but like fraction

you will need to whitelist it in your database
