### ISSUE TITLE
NO NPC

### ISSUE THREAD

**Issue by Brabus453** [FuryFight3r/dgrp_mcdonaldsjob#3]
i installed and followed instructions.

I disabled Players, and set NPC on. but still they dont show...

any idea?

these are my settings:

Config.EnablePlayerJobs		= false		--Enables Jobs for Players to use.
Config.EnablePlayerCook		= false		--Cook gets drinks, makes burgers and fries and gives to clerk both for NPC orders and Player orders.
Config.EnablePlayerClerk	= false		--Clerk receives orders, gives to cook, receives orders from cook, and gives to customer. 				
Config.EnablePlayerDriver	= false		--Driver delivers orders marked for delivery.

Config.CashJobLimit			= 3			--The amount of staff that can be in a job at a time
Config.CookJobLimit			= 3			--			    "                "
Config.DelivJobLimit		= 7			--			    "                "

Config.EnableNPCWorkers		= true		--NPC Workers are there if player jobs are disabled -- Coming Soon
Config.EnableNPCOrders		= false		--MUST be false if player jobs are disabled, gives RP NPC orders for players to undertake -- Coming Soon

Config.NPCDespawnTime		= 5			--Minutes until NPC gets deleted // DOESNT WORK! NEEDS FIXING

**Comment by FuryFight3r** [comment]
There are no NPC jobs at the moment, only NPC customers, that again are really buggy at the moment and dont get removed. Next time use the template, I will start refusong to help people that dont use it, it makes things so much harder and just wastes my time, thank you.

**Comment by FuryFight3r** [comment]
All functions that do nothing have now been removed from the config so that people who do not like reading, do not get confused.
