### ISSUE TITLE
cashier job not working properly[HELP]

### ISSUE THREAD

**Issue by KilianLietaert** [FuryFight3r/dgrp_mcdonaldsjob#4]
**Please do NOT remove any text from the template.**
Add your title and add your answers below, if you have more information by all means add it, but do not remove any details already existing below, this will void your request and we will not respond if it is not filled out correctly.

**Disclaimer**
Due to the fact that people are providing such little information and expecting us to be able to fix their problem, we are now enforcing these issue templates through github, if you fill these forms out incorrectly or provide little information, then expect little help in return, we, as addon creators spend hours/days/weeks and even months and years doing this for FREE, both creating addons and giving support, so please show some courtesy and atleast have a fair go at diagnosing and fixing your problem before creating a post and possibly wasting not only your own time, but the people that are trying to create resources for server owners like you. 

**FAQ - (Frequently Asked Questions)**
Q: Why is nothing showing up but I have the McDonalds Job?
A: This is likely due to the fact that you have spelt the resource incorrectly in your server.cfg meaning the resource has failed to start check for any errors in your server.

Q: Why does rain come inside the building?
A: This happens with all YMAP Map Mods, please create your own building if this is a problem

**Game Versions**
Do you own a Legitimate copy of GTA?
Anwser: yes
What version of GTA do you own(Social Club, Steam, Epic)?
Answer: epic
Are both GTA and FiveM Currently using the latest Version?
Answer: yes

**Resource Versions**
What ESX Version are you using?
ESX Version: v1-final
Did you read the Addon Requirements and are you using said required addons?
Answer: yes
Furthermore did you read and understand the entire github README.MD?
Answer: yes
Are the addons that this resource requires and the DGRP_McDonaldsJob up-to-date?
Answer: yes

**System/Server Specs**
What are your system/server specs?
Home Hosted or Server Hosted(Zap Hosted)?
Answer: server hosted
(if Home Hosted answer below questions)
Operating System:
RAM:
GPU:
CPU:

**Describe the problem**
A clear and concise description of what the problem is.
Describe: the cook and delivery works fine, but the cahsier job can take customer order if you did that u can see that you have to go take the meal, but if you press E there, nothing happens, i also get no errors, it just does not want to grab the meal.

**Screenshots**
Add screenshots to help explain your problem.
Screenshots:

**Extra Details**
Did you modify any DGRP_McDonaldsJob scripts in anyway(besides the config)?
Answer: no
Is the entire server receiving this problem or only you?
Answer: entire server
Have you tried the basic diagnotics such as typing in chat '/restart dgrp_mcdonaldsjob' then '/setjob ID McDonalds 1' also restarting your server?
Answer: yes
If you answered yes to the above are you receiving any errors in the 'f8' console or the server console in relation to dgrp_mcdonaldsjob when restarting the resource or setting your job?
Answer: no
If you answered yes to the above what error are you receiving and did you provide a sceenshot of it?
Answer:

**READ**
Did you read the FAQ's to make sure your not asking something that is already frequently asked?
Answer: yes

**Comment by FuryFight3r** [comment]
Great thank you for filling out the template, can you please confirm that when you take a customers order as a cashier, that no error in the 'f8' client console has come up, aswell as inside the server console, this is more difficult to find on a zap hosted server, your looking for an icon on the servers website that looks like a black box with I believe green text on it, normally what a console looks like and confirm that there is no error there too if you could please.

**Comment by KilianLietaert** [comment]
yes i can confirm that there are no errors in my console

**Comment by FuryFight3r** [comment]
May I ask which 'Console' you are referring to? As their should be 2 that you need to look at for errors

**Comment by KilianLietaert** [comment]
nevermind man it does work, i was just really stupid, sorry to bother you man

**Comment by FuryFight3r** [comment]
No trouble, im glad its working, all the best! ☺👍
