### ISSUE TITLE
[SUGGESTION] Delivery Drivers and Work Vehicles

### ISSUE THREAD

**Issue by Timmyopp** [FuryFight3r/dgrp_mcdonaldsjob#5]
**Please do NOT remove any text from the template.**
Please add your title and add your answers below, if you have more information by all means add it, but do not remove any details already existing below, this will void your request and we will not respond if it is not filled out correctly.

**Disclaimer**
Due to the fact that many people are providing such little information and expecting us to be able to fix their problem, we are now enforcing these issue templates through github, if you fill these forms out incorrectly or provide little information, then expect little help in return, we, as addon creators spend days or weeks and even months or years doing this for FREE, both creating addons and giving support, so please show some courtesy and atleast have a fair go at diagnosing and fixing your problem before creating a post and possibly wasting not only your own time, but the people that are trying to create resources for server owners like you.
I have event spent a few hours alone creating these templates to avoid the generic, frutsrating server newbies that avoid doing the most basic diagnostics it's laughable.
So long story short, if you actually take the time to read this template it may even solve your issue before you need to create one.
Let's start with the Frequently Asked Questions.

**FAQ - (Frequently Asked Questions)**
Q: Why is nothing showing up but I have the McDonalds Job?
A: This is likely due to the fact that you have spelt the resource incorrectly in your server.cfg meaning the resource has failed to start check for any errors in your server.

Q: Why does rain come inside the building?
A: This happens with all YMAP Map Mods, please create your own building if this is a problem

Q: How do I find my Zap-Hosting Server Console so I can see error print outs?
A: https://forum.cfx.re/uploads/default/original/3X/b/b/bbbaab5b2a6ada72657faa62acfbe564c21275b3.png - If you dont see a visable error, scroll up until you find where dgrp_mcdonaldsjob should have started and see if there is an error there.

Q: I did the above and I am receiving an error of 'missing dependecy...' what does this mean?
A: This means you are missing a REQUIRED addon please go back to the dgrp_mcdonaldsjob GitHub Main Page and look at the REQUIREMENTS section, these requirements are REQUIRED for this McDonalds Job to work.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**READ**
Did you read the FAQ's to make sure your not asking something that is already frequently asked?
Answer: Yes

**Additional context**
Add any other context or screenshots about the suggestion here.
I think you should change the vehicle delivery option cause people can drive with any car to deliveries, and most of them not using the car spawn.
The second thing is people can eat the "Delivery Meal" that they are making for the delivery job, and even after they ate it they can drive to delivery and get paid for delivering nothing at all.
Thank you sincerely for taking the time to read and fill out this template.

**Comment by FuryFight3r** [comment]
Thank you very much for bringing this up, I intentionally made it to use either a player owned or work vehicle, I am not sure how I would be able to force them to use the McDonalds Vehicle, but if people are only using player vehicles I would like to make it atleast more preferable to choose the work vehicles, also great pick up on eating the orders, I honestly didnt even think of that, I know two ways of overcoming this, not allowing to eat a meal while on delivery, or make it so they can eat it, but then instead of them earning money for the job, they have to pay for the meal and delivery. What do you think would be better? Making them pay would be easier to implement, it would be hard to not allow them to eat a certain object as that is handled through basicneeds, or status. But again thank you so much for both using the template and giving a great suggestion. ☺👍

**Comment by Timmyopp** [comment]
My opinion is to force them use work vehicles and disable marker if you're not in work car.
About the second thing making the meal uneatable is not the good way of fixing it cause it's food :)
You can make it cost money to create that meal for like 1500 and then they won't eat it cause delivering it will cost more than 2000 for example.
And yes, you can't cover everything when coding most of the issues comes when players test it and devs can see the issues.
Thanks for your work! Waiting for an update.

**Comment by Timmyopp** [comment]
Also check that bug when they eat it and still can deliver. The delivery should be gone if the player eat it or losing the delivery meal.

**Comment by Timmyopp** [comment]
Can you send me your discord?

**Comment by FuryFight3r** [comment]
Great, thank you! I unfortunately do not have a public discord server, as I tend to get too many requests to build a server or make custom addons and most of the time I will only get offered a 'Developer' or 'Moderator' tag on their server, which I for the most part have no intention of playing or being apart of. So it takes me away from what I love doing, which is developing mods that are unique as apose to the generic stuff that you see on every single server... I apologize for the rant hahah but I hope you understand.. I will do my best to fix these errors and will update as soon as possible, thanks again!

**Comment by FuryFight3r** [comment]
Above suggestions have now been implemented, you will be able to download the new version on github, thanks again!
