### ISSUE TITLE
[BUG] Delivery job

### ISSUE THREAD

**Issue by Timmyopp** [FuryFight3r/dgrp_mcdonaldsjob#6]
Hey its me again :)
Sorry for not using all the template again, but some of my players and also me having a bug on delivery job.
After you make the meal, spawn your vehicle and get inside, there is no GPS showing where to drive.
Not sure why is this happening but restarting the script fix the problem for them and also for myself while checking the bug.

I can provide more information if needed on my discord - Timmy#8488

The last update was awesome and fixed most of the issues I posted before, thanks for everything!

**Comment by FuryFight3r** [comment]
Hmm, this is becoming a major problem ever since I added Props and NPC's, ever since Ive added the Probs and NPCs it seems every new feature I add the script needs to be restarted after its initial start, to get these new functions working which makes no sense to me, ive been trying to find a solution for weeks but am unable to find any problems in the scripting, I will create a help post on the CFX forum and see if anyone can help us out, thanks for bringing this up I will let you know if we can or can't fix it.

**Comment by Timmyopp** [comment]
Is there any news? I think better reverting back to previous version since this delivery bug happens too often.

**Comment by FuryFight3r** [comment]
Unfortunately no I have not heard anything yet, it can take months to get help with advanced stuff like this, I waited nearly 2 months for help with my advanced version, turns out it was the most simple thing, just not many helpers out there, thats the main problem

**Comment by Timmyopp** [comment]
Still trying to find the fix for this issue, even after re-log or dropping the delivery meal and getting a new one is not helping.
But, If they get rid of the meals and then I restart the script and then they get a new meal it works, Only for people that are online in the same time I restart it.

**Comment by Danny9865** [comment]
![image](https://user-images.githubusercontent.com/58650168/89406117-96f24900-d714-11ea-8d94-1838626ed34d.png)

this fixes that guys

**Comment by Timmyopp** [comment]
@FuryFight3r You can check that and verify it that works.

I will also implement this fix on my version and post here in the next few days if that helped.

Thanks @Danny9865

**Comment by Danny9865** [comment]
worth looking into mohitos method, definitely a lot better

**Comment by ElTomaToV2** [comment]
![script mcdo](https://user-images.githubusercontent.com/73359364/97035949-5feb4100-1567-11eb-857c-cc36cf15e525.png)
Hello,
I found why the delivery point is not showing, look at the screenshot, I circled it in red ^^
