### ISSUE TITLE
14mdvmb Error , please help

### ISSUE THREAD

**Issue by KeepDev20** [FuryFight3r/dgrp_mcdonaldsjob#8]
Hello, I have put this system on my server but when starting the script I get the error 14mdvmb, I request urgent help, greetings.

**Comment by Mojito-Fivem** [comment]
This isn't an error at all, this is just the Original Dev being a bit of a cunt and making it so that if you re-name the resource it prints to the server consolve with the error code "14mdvmb" or "I am dumb". You can solve this by removing the check for this in the server side of this resource.

**Comment by dragonDScript** [comment]
My question is; why would you release an open source repo which only works on your own server?

**Comment by FuryFight3r** [comment]
Maybe you just have no clue what you're doing, thousands of people have downloaded and are currently using this addon.. 🤷‍♂️

**Comment by dragonDScript** [comment]
They're breaking the license...but I know what you mean
